'use strict';
/* ECHOFALL offline cache (generated by tools/package.py — do not edit the copy in a build).
   Versioned files are cached on first launch so home-screen launches open instantly; the page itself and
   version.json always try the network first, which is how new releases arrive (js/update.js reloads, and the
   new index.html asks for the new ?v= files). */
const CACHE = 'echofall-26f3866e11';
const ASSETS = ["./", "index.html", "manifest.webmanifest", "css/style.css?v=26f3866e11", "js/audio.js?v=26f3866e11", "js/boons.js?v=26f3866e11", "js/chapters.js?v=26f3866e11", "js/core.js?v=26f3866e11", "js/data.js?v=26f3866e11", "js/enemies.js?v=26f3866e11", "js/fullscreen.js?v=26f3866e11", "js/fx.js?v=26f3866e11", "js/game.js?v=26f3866e11", "js/gear.js?v=26f3866e11", "js/gear_ui.js?v=26f3866e11", "js/player.js?v=26f3866e11", "js/rig.js?v=26f3866e11", "js/touch.js?v=26f3866e11", "js/tutorial.js?v=26f3866e11", "js/ui.js?v=26f3866e11", "js/update.js?v=26f3866e11", "js/world.js?v=26f3866e11", "js/chapters/ch1_foes.js?v=26f3866e11", "js/chapters/ch2.js?v=26f3866e11", "js/chapters/ch2_boss.js?v=26f3866e11", "js/chapters/ch2_foes.js?v=26f3866e11", "js/chapters/ch3.js?v=26f3866e11", "js/chapters/ch3_boss.js?v=26f3866e11", "js/chapters/ch3_foes.js?v=26f3866e11", "js/chapters/ch4.js?v=26f3866e11", "js/chapters/ch4_boss.js?v=26f3866e11", "js/chapters/ch4_foes.js?v=26f3866e11", "js/chapters/ch5.js?v=26f3866e11", "js/chapters/ch5_boss.js?v=26f3866e11", "js/chapters/ch5_foes.js?v=26f3866e11", "js/chapters/ch6.js?v=26f3866e11", "js/chapters/ch6_boss.js?v=26f3866e11", "js/chapters/ch6_foes.js?v=26f3866e11", "js/chapters/ch7.js?v=26f3866e11", "js/chapters/ch7_boss.js?v=26f3866e11", "js/chapters/ch7_foes.js?v=26f3866e11", "js/chapters/ch8.js?v=26f3866e11", "js/chapters/ch8_boss.js?v=26f3866e11", "js/chapters/ch8_foes.js?v=26f3866e11", "icons/icon-180.png", "icons/icon-192.png", "icons/icon-512.png"];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const u = new URL(e.request.url);
  if (e.request.method !== 'GET' || u.origin !== location.origin || u.pathname.endsWith('version.json')) return;
  if (e.request.mode === 'navigate') {
    e.respondWith(fetch(e.request).then((r) => {
      const c = r.clone(); caches.open(CACHE).then((k) => k.put('index.html', c)); return r;
    }).catch(() => caches.match('index.html')));
    return;
  }
  e.respondWith(caches.match(e.request).then((hit) => hit || fetch(e.request).then((r) => {
    if (r.ok) { const c = r.clone(); caches.open(CACHE).then((k) => k.put(e.request, c)); }
    return r;
  })));
});
